[package]
name = "weatherapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.1.8", features = ["desktop"] }
tokio = { version = "1.15.0", features = ["full"] }
